// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  challengeId: __t.u64().primaryKey().name("challenge_id"),
  fromId: __t.u64().name("from_id"),
  fromName: __t.string().name("from_name"),
  toId: __t.u64().name("to_id"),
  toName: __t.string().name("to_name"),
  created: __t.timestamp(),
});
