// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  effectId: __t.u64().primaryKey().name("effect_id"),
  gameId: __t.u64().name("game_id"),
  ts: __t.timestamp(),
  kind: __t.u8(),
  actorColor: __t.u8().name("actor_color"),
  card: __t.u8(),
  aSq: __t.u8().name("a_sq"),
  bSq: __t.u8().name("b_sq"),
});
