// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  gameId: __t.u64().primaryKey().name("game_id"),
  whiteId: __t.u64().name("white_id"),
  blackId: __t.u64().name("black_id"),
  whiteName: __t.string().name("white_name"),
  blackName: __t.string().name("black_name"),
  phase: __t.u8(),
  startedAt: __t.timestamp().name("started_at"),
  result: __t.u8(),
  resultReason: __t.u8().name("result_reason"),
  whiteInCheck: __t.bool().name("white_in_check"),
  blackInCheck: __t.bool().name("black_in_check"),
  whiteMated: __t.bool().name("white_mated"),
  blackMated: __t.bool().name("black_mated"),
  whiteDrawOffer: __t.bool().name("white_draw_offer"),
  blackDrawOffer: __t.bool().name("black_draw_offer"),
});
