// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.5.0 (commit ca16958ef0a5f8c816700d2255a0b20ecacff901).

/* eslint-disable */
/* tslint:disable */
import {
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TypeBuilder as __TypeBuilder,
  Uuid as __Uuid,
  convertToAccessorMap as __convertToAccessorMap,
  makeQueryBuilder as __makeQueryBuilder,
  procedureSchema as __procedureSchema,
  procedures as __procedures,
  reducerSchema as __reducerSchema,
  reducers as __reducers,
  schema as __schema,
  t as __t,
  table as __table,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type DbConnectionConfig as __DbConnectionConfig,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type Infer as __Infer,
  type QueryBuilder as __QueryBuilder,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type RemoteModule as __RemoteModule,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type SubscriptionHandleImpl as __SubscriptionHandleImpl,
} from "spacetimedb";

// Import all reducer arg schemas
import AcceptChallengeReducer from "./accept_challenge_reducer";
import BuyCardCopyReducer from "./buy_card_copy_reducer";
import BuySkinReducer from "./buy_skin_reducer";
import CreateChallengeReducer from "./create_challenge_reducer";
import DeclineChallengeReducer from "./decline_challenge_reducer";
import DeleteLoadoutReducer from "./delete_loadout_reducer";
import EquipSkinReducer from "./equip_skin_reducer";
import GrantPurchaseReducer from "./grant_purchase_reducer";
import JoinQueueReducer from "./join_queue_reducer";
import LeaveQueueReducer from "./leave_queue_reducer";
import LoginReducer from "./login_reducer";
import LogoutReducer from "./logout_reducer";
import MovePieceReducer from "./move_piece_reducer";
import OfferDrawReducer from "./offer_draw_reducer";
import PlayCardReducer from "./play_card_reducer";
import RegisterReducer from "./register_reducer";
import ResignReducer from "./resign_reducer";
import SaveLoadoutReducer from "./save_loadout_reducer";
import SendChatReducer from "./send_chat_reducer";
import SetActiveLoadoutReducer from "./set_active_loadout_reducer";
import SetOperatorReducer from "./set_operator_reducer";
import SpectateReducer from "./spectate_reducer";
import StopSpectatingReducer from "./stop_spectating_reducer";

// Import all procedure arg schemas

// Import all table schema definitions
import ChallengeRow from "./challenge_table";
import ChatMessageRow from "./chat_message_table";
import EffectLogRow from "./effect_log_table";
import GameRow from "./game_table";
import GameGemsRow from "./game_gems_table";
import MoveLogRow from "./move_log_table";
import MyCardStateRow from "./my_card_state_table";
import MyCardsRow from "./my_cards_table";
import MyLoadoutsRow from "./my_loadouts_table";
import MySkinsRow from "./my_skins_table";
import MyWalletRow from "./my_wallet_table";
import PieceRow from "./piece_table";
import PlayerProfileRow from "./player_profile_table";
import QueueEntryRow from "./queue_entry_table";
import RatingHistoryRow from "./rating_history_table";
import SessionRow from "./session_table";
import SkinCatalogRow from "./skin_catalog_table";
import SpectatorRow from "./spectator_table";

/** Type-only namespace exports for generated type groups. */

/** The schema information for all tables in this module. This is defined the same was as the tables would have been defined in the server. */
const tablesSchema = __schema({
  challenge: __table({
    name: 'challenge',
    indexes: [
      { accessor: 'challenge_id', name: 'challenge_challenge_id_idx_btree', algorithm: 'btree', columns: [
        'challengeId',
      ] },
      { accessor: 'from_id', name: 'challenge_from_id_idx_btree', algorithm: 'btree', columns: [
        'fromId',
      ] },
      { accessor: 'to_id', name: 'challenge_to_id_idx_btree', algorithm: 'btree', columns: [
        'toId',
      ] },
    ],
    constraints: [
      { name: 'challenge_challenge_id_key', constraint: 'unique', columns: ['challengeId'] },
    ],
  }, ChallengeRow),
  chat_message: __table({
    name: 'chat_message',
    indexes: [
      { accessor: 'channel', name: 'chat_message_channel_idx_btree', algorithm: 'btree', columns: [
        'channel',
      ] },
      { accessor: 'game_id', name: 'chat_message_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'msg_id', name: 'chat_message_msg_id_idx_btree', algorithm: 'btree', columns: [
        'msgId',
      ] },
    ],
    constraints: [
      { name: 'chat_message_msg_id_key', constraint: 'unique', columns: ['msgId'] },
    ],
  }, ChatMessageRow),
  effect_log: __table({
    name: 'effect_log',
    indexes: [
      { accessor: 'effect_id', name: 'effect_log_effect_id_idx_btree', algorithm: 'btree', columns: [
        'effectId',
      ] },
      { accessor: 'game_id', name: 'effect_log_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
    ],
    constraints: [
      { name: 'effect_log_effect_id_key', constraint: 'unique', columns: ['effectId'] },
    ],
  }, EffectLogRow),
  game: __table({
    name: 'game',
    indexes: [
      { accessor: 'black_id', name: 'game_black_id_idx_btree', algorithm: 'btree', columns: [
        'blackId',
      ] },
      { accessor: 'game_id', name: 'game_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'white_id', name: 'game_white_id_idx_btree', algorithm: 'btree', columns: [
        'whiteId',
      ] },
    ],
    constraints: [
      { name: 'game_game_id_key', constraint: 'unique', columns: ['gameId'] },
    ],
  }, GameRow),
  game_gems: __table({
    name: 'game_gems',
    indexes: [
      { accessor: 'game_id', name: 'game_gems_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'game_gems_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'game_gems_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, GameGemsRow),
  move_log: __table({
    name: 'move_log',
    indexes: [
      { accessor: 'game_id', name: 'move_log_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'move_id', name: 'move_log_move_id_idx_btree', algorithm: 'btree', columns: [
        'moveId',
      ] },
    ],
    constraints: [
      { name: 'move_log_move_id_key', constraint: 'unique', columns: ['moveId'] },
    ],
  }, MoveLogRow),
  piece: __table({
    name: 'piece',
    indexes: [
      { accessor: 'game_id', name: 'piece_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'piece_id', name: 'piece_piece_id_idx_btree', algorithm: 'btree', columns: [
        'pieceId',
      ] },
    ],
    constraints: [
      { name: 'piece_piece_id_key', constraint: 'unique', columns: ['pieceId'] },
    ],
  }, PieceRow),
  player_profile: __table({
    name: 'player_profile',
    indexes: [
      { accessor: 'account_id', name: 'player_profile_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'player_profile_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, PlayerProfileRow),
  queue_entry: __table({
    name: 'queue_entry',
    indexes: [
      { accessor: 'account_id', name: 'queue_entry_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
    ],
    constraints: [
      { name: 'queue_entry_account_id_key', constraint: 'unique', columns: ['accountId'] },
    ],
  }, QueueEntryRow),
  rating_history: __table({
    name: 'rating_history',
    indexes: [
      { accessor: 'account_id', name: 'rating_history_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'id', name: 'rating_history_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'rating_history_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, RatingHistoryRow),
  session: __table({
    name: 'session',
    indexes: [
      { accessor: 'account_id', name: 'session_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'identity', name: 'session_identity_idx_btree', algorithm: 'btree', columns: [
        'identity',
      ] },
    ],
    constraints: [
      { name: 'session_identity_key', constraint: 'unique', columns: ['identity'] },
    ],
  }, SessionRow),
  skin_catalog: __table({
    name: 'skin_catalog',
    indexes: [
      { accessor: 'skin_id', name: 'skin_catalog_skin_id_idx_btree', algorithm: 'btree', columns: [
        'skinId',
      ] },
    ],
    constraints: [
      { name: 'skin_catalog_skin_id_key', constraint: 'unique', columns: ['skinId'] },
    ],
  }, SkinCatalogRow),
  spectator: __table({
    name: 'spectator',
    indexes: [
      { accessor: 'account_id', name: 'spectator_account_id_idx_btree', algorithm: 'btree', columns: [
        'accountId',
      ] },
      { accessor: 'game_id', name: 'spectator_game_id_idx_btree', algorithm: 'btree', columns: [
        'gameId',
      ] },
      { accessor: 'id', name: 'spectator_id_idx_btree', algorithm: 'btree', columns: [
        'id',
      ] },
    ],
    constraints: [
      { name: 'spectator_id_key', constraint: 'unique', columns: ['id'] },
    ],
  }, SpectatorRow),
  my_card_state: __table({
    name: 'my_card_state',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCardStateRow),
  my_cards: __table({
    name: 'my_cards',
    indexes: [
    ],
    constraints: [
    ],
  }, MyCardsRow),
  my_loadouts: __table({
    name: 'my_loadouts',
    indexes: [
    ],
    constraints: [
    ],
  }, MyLoadoutsRow),
  my_skins: __table({
    name: 'my_skins',
    indexes: [
    ],
    constraints: [
    ],
  }, MySkinsRow),
  my_wallet: __table({
    name: 'my_wallet',
    indexes: [
    ],
    constraints: [
    ],
  }, MyWalletRow),
});

/** The schema information for all reducers in this module. This is defined the same way as the reducers would have been defined in the server, except the body of the reducer is omitted in code generation. */
const reducersSchema = __reducers(
  __reducerSchema("accept_challenge", AcceptChallengeReducer),
  __reducerSchema("buy_card_copy", BuyCardCopyReducer),
  __reducerSchema("buy_skin", BuySkinReducer),
  __reducerSchema("create_challenge", CreateChallengeReducer),
  __reducerSchema("decline_challenge", DeclineChallengeReducer),
  __reducerSchema("delete_loadout", DeleteLoadoutReducer),
  __reducerSchema("equip_skin", EquipSkinReducer),
  __reducerSchema("grant_purchase", GrantPurchaseReducer),
  __reducerSchema("join_queue", JoinQueueReducer),
  __reducerSchema("leave_queue", LeaveQueueReducer),
  __reducerSchema("login", LoginReducer),
  __reducerSchema("logout", LogoutReducer),
  __reducerSchema("move_piece", MovePieceReducer),
  __reducerSchema("offer_draw", OfferDrawReducer),
  __reducerSchema("play_card", PlayCardReducer),
  __reducerSchema("register", RegisterReducer),
  __reducerSchema("resign", ResignReducer),
  __reducerSchema("save_loadout", SaveLoadoutReducer),
  __reducerSchema("send_chat", SendChatReducer),
  __reducerSchema("set_active_loadout", SetActiveLoadoutReducer),
  __reducerSchema("set_operator", SetOperatorReducer),
  __reducerSchema("spectate", SpectateReducer),
  __reducerSchema("stop_spectating", StopSpectatingReducer),
);

/** The schema information for all procedures in this module. This is defined the same way as the procedures would have been defined in the server. */
const proceduresSchema = __procedures(
);

/** The remote SpacetimeDB module schema, both runtime and type information. */
const REMOTE_MODULE = {
  versionInfo: {
    cliVersion: "2.5.0" as const,
  },
  tables: tablesSchema.schemaType.tables,
  reducers: reducersSchema.reducersType.reducers,
  ...proceduresSchema,
} satisfies __RemoteModule<
  typeof tablesSchema.schemaType,
  typeof reducersSchema.reducersType,
  typeof proceduresSchema
>;

/** The tables available in this remote SpacetimeDB module. Each table reference doubles as a query builder. */
export const tables: __QueryBuilder<typeof tablesSchema.schemaType> = __makeQueryBuilder(tablesSchema.schemaType);

/** The reducers available in this remote SpacetimeDB module. */
export const reducers = __convertToAccessorMap(reducersSchema.reducersType.reducers);

/** The procedures available in this remote SpacetimeDB module. */
export const procedures = __convertToAccessorMap(proceduresSchema.procedures);

/** The context type returned in callbacks for all possible events. */
export type EventContext = __EventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for reducer events. */
export type ReducerEventContext = __ReducerEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for subscription events. */
export type SubscriptionEventContext = __SubscriptionEventContextInterface<typeof REMOTE_MODULE>;
/** The context type returned in callbacks for error events. */
export type ErrorContext = __ErrorContextInterface<typeof REMOTE_MODULE>;
/** The subscription handle type to manage active subscriptions created from a {@link SubscriptionBuilder}. */
export type SubscriptionHandle = __SubscriptionHandleImpl<typeof REMOTE_MODULE>;

/** Builder class to configure a new subscription to the remote SpacetimeDB instance. */
export class SubscriptionBuilder extends __SubscriptionBuilderImpl<typeof REMOTE_MODULE> {}

/** Builder class to configure a new database connection to the remote SpacetimeDB instance. */
export class DbConnectionBuilder extends __DbConnectionBuilder<DbConnection> {}

/** The typed database connection to manage connections to the remote SpacetimeDB instance. This class has type information specific to the generated module. */
export class DbConnection extends __DbConnectionImpl<typeof REMOTE_MODULE> {
  /** Creates a new {@link DbConnectionBuilder} to configure and connect to the remote SpacetimeDB instance. */
  static builder = (): DbConnectionBuilder => {
    return new DbConnectionBuilder(REMOTE_MODULE, (config: __DbConnectionConfig<typeof REMOTE_MODULE>) => new DbConnection(config));
  };

  /** Creates a new {@link SubscriptionBuilder} to configure a subscription to the remote SpacetimeDB instance. */
  override subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  };
}

