// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  moveId: __t.u64().primaryKey().name("move_id"),
  gameId: __t.u64().name("game_id"),
  seq: __t.u32(),
  ts: __t.timestamp(),
  color: __t.u8(),
  fromSq: __t.u8().name("from_sq"),
  toSq: __t.u8().name("to_sq"),
  capturedTy: __t.u8().name("captured_ty"),
  boardAfter: __t.string().name("board_after"),
});
