// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Account = __t.object("Account", {
  accountId: __t.u64(),
  usernameLower: __t.string(),
  username: __t.string(),
  passHash: __t.string(),
  createdAt: __t.timestamp(),
});
export type Account = __Infer<typeof Account>;

export const AuthThrottle = __t.object("AuthThrottle", {
  identity: __t.identity(),
  fails: __t.u32(),
  lockedUntil: __t.timestamp(),
});
export type AuthThrottle = __Infer<typeof AuthThrottle>;

export const BoardSnapshot = __t.object("BoardSnapshot", {
  id: __t.u64(),
  gameId: __t.u64(),
  ts: __t.timestamp(),
  seq: __t.u32(),
  board: __t.string(),
  moved: __t.string(),
});
export type BoardSnapshot = __Infer<typeof BoardSnapshot>;

export const EffectLog = __t.object("EffectLog", {
  effectId: __t.u64(),
  gameId: __t.u64(),
  ts: __t.timestamp(),
  kind: __t.u8(),
  actorColor: __t.u8(),
  card: __t.u8(),
  aSq: __t.u8(),
  bSq: __t.u8(),
});
export type EffectLog = __Infer<typeof EffectLog>;

export const ForfeitTimer = __t.object("ForfeitTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
  accountId: __t.u64(),
});
export type ForfeitTimer = __Infer<typeof ForfeitTimer>;

export const Game = __t.object("Game", {
  gameId: __t.u64(),
  whiteId: __t.u64(),
  blackId: __t.u64(),
  whiteName: __t.string(),
  blackName: __t.string(),
  phase: __t.u8(),
  startedAt: __t.timestamp(),
  result: __t.u8(),
  resultReason: __t.u8(),
  whiteInCheck: __t.bool(),
  blackInCheck: __t.bool(),
  whiteMated: __t.bool(),
  blackMated: __t.bool(),
  whiteDrawOffer: __t.bool(),
  blackDrawOffer: __t.bool(),
});
export type Game = __Infer<typeof Game>;

export const GameCardState = __t.object("GameCardState", {
  id: __t.u64(),
  gameId: __t.u64(),
  accountId: __t.u64(),
  deck: __t.byteArray(),
  hand: __t.byteArray(),
  discard: __t.byteArray(),
});
export type GameCardState = __Infer<typeof GameCardState>;

export const GameGems = __t.object("GameGems", {
  id: __t.u64(),
  gameId: __t.u64(),
  accountId: __t.u64(),
  base: __t.u8(),
  anchor: __t.timestamp(),
});
export type GameGems = __Infer<typeof GameGems>;

export const GameStartTimer = __t.object("GameStartTimer", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  gameId: __t.u64(),
});
export type GameStartTimer = __Infer<typeof GameStartTimer>;

export const MoveLog = __t.object("MoveLog", {
  moveId: __t.u64(),
  gameId: __t.u64(),
  seq: __t.u32(),
  ts: __t.timestamp(),
  color: __t.u8(),
  fromSq: __t.u8(),
  toSq: __t.u8(),
  capturedTy: __t.u8(),
  boardAfter: __t.string(),
});
export type MoveLog = __Infer<typeof MoveLog>;

export const Piece = __t.object("Piece", {
  pieceId: __t.u64(),
  gameId: __t.u64(),
  ty: __t.u8(),
  color: __t.u8(),
  sq: __t.u8(),
  hasMoved: __t.bool(),
  cooldownUntil: __t.timestamp(),
  shielded: __t.bool(),
});
export type Piece = __Infer<typeof Piece>;

export const QueueEntry = __t.object("QueueEntry", {
  accountId: __t.u64(),
  username: __t.string(),
  queuedAt: __t.timestamp(),
});
export type QueueEntry = __Infer<typeof QueueEntry>;

export const Session = __t.object("Session", {
  identity: __t.identity(),
  accountId: __t.u64(),
  username: __t.string(),
  online: __t.bool(),
  connections: __t.u32(),
  status: __t.u8(),
});
export type Session = __Infer<typeof Session>;

